name: CI Pipeline

on:
  # push:
  #   branches: [main]
  #   paths: ["**.py", "pyproject.toml", "tox.ini", ".pre-commit.yaml"]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Run tests and checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run pre-commit hooks
        run: poetry run pre-commit run --all-files --config=.pre-commit.yml

      - name: Run tests with coverage
        run: poetry run pytest --cov=axcer --cov-report=xml

      - name: Upload coverage report
        if: success()
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: true

      - name: Run Tox
        run: poetry run tox
